.TH logtime 1 logtime\-0.0.1
.SH NAME
logtime, calctime \- log and calculate billable hours
.SH SYNOPSIS
.B calctime [OPTIONS] FILE 
.br
.B logtime [OPTIONS] FILE
.SH DESCRIPTION
.B 
.B logtime
!WHAT IT DOES!
.SH OPTIONS
none
.SH EXAMPLES
.B logtime 
!INVOCATIONS!
.SH FILES
.SH SEE ALSO
.SH BUGS
Probably.
.SH LICENSE
Copyright 2013 
.sp
You may use this software however you like.
