#!/bin/ruby
#
require 'date'
#
a = DateTime.new(2013 , 02 , 27 , 12 , 28) - DateTime.new(2013 , 02 , 27 , 10 , 00)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 27 , 14 , 01) - DateTime.new(2013 , 02 , 27 , 12 , 47)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 27 , 14 , 31) - DateTime.new(2013 , 02 , 27 , 14 , 16)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 27 , 14 , 58) - DateTime.new(2013 , 02 , 27 , 14 , 48)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 27 , 16 , 11) - DateTime.new(2013 , 02 , 27 , 15 , 41)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 28 , 6 , 58) - DateTime.new(2013 , 02 , 28 , 6 , 51)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 28 , 8 , 50) - DateTime.new(2013 , 02 , 28 , 8 , 34)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 28 , 9 , 41) - DateTime.new(2013 , 02 , 28 , 9 , 00)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 02 , 28 , 15 , 55) - DateTime.new(2013 , 02 , 28 , 14 , 31)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 01 , 9 , 29) - DateTime.new(2013 , 03 , 01 , 8 , 45)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 01 , 10 , 21) - DateTime.new(2013 , 03 , 01 , 9 , 49)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 01 , 12 , 13) - DateTime.new(2013 , 03 , 01 , 12 , 10)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 01 , 12 , 58) - DateTime.new(2013 , 03 , 01 , 12 , 38)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 04 , 6 , 47) - DateTime.new(2013 , 03 , 04 , 6 , 45)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 04 , 8 , 39) - DateTime.new(2013 , 03 , 04 , 8 , 26)
puts (a * 24 * 60).to_i

a = DateTime.new(2013 , 03 , 04 , 15 , 59) - DateTime.new(2013 , 03 , 04 , 15 , 53)
puts (a * 24 * 60).to_i


