.TH logtime 1 logtime\-0.0.1
.SH NAME
logtime \- log time intervals
.SH SYNOPSIS
.B logtime [OPTIONS] FILE
.SH DESCRIPTION
.B logtime
is not yet implemented,
but is intended to create files appropriate for use by
.SH OPTIONS
.SH EXAMPLES
.SH FILES
.SH SEE ALSO
.B ruby(1)
.SH BUGS
Probably.
.SH LICENSE
Copyright 2013 
.sp
You may use this software however you like.
