.TH logtime 1 logtime\-0.0.1
.SH NAME
logtime \- log time intervals
.SH SYNOPSIS
.B logtime [OPTIONS] b|e [FILE [MESSAGE]]
.SH DESCRIPTION
.B logtime
logs the current time and an optional message to
.B FILE
in the logtime config directory
(see
.B FILES
below, and 
.B -o FILE
).
.B FILE 
is intended to be parsed by 
.B calctime(1),
but is easily human readable.
.SH OPTIONS
.B e
log end time.
.br
.B b
log begin time.
.br
.B -f
force \(em
don't check if we are correctly starting or stopping an interval.
.br
.B -o FILE
write to 
.B FILE
(relative or absolute path)
rather than the file in the config directory.
.br
.SH EXAMPLES
logtime b work Now I am starting this project
.br
calctime --check-status work     # Not sure if I am clocked in or not
.br
logtime e work Now I finished the project
.br
calctime -v work
.SH FILES
.B $HOME/.config/logtime
the directory where logfiles are stored by default.
.SH SEE ALSO
.B calctime(1)
.SH BUGS
Probably.
.SH LICENSE
Copyright 2013 
.sp
You may use this software however you like.
